version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - 9000:9000
    volumes:
      - .:/var/www
  webserver:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
